version: "3.1"
services:
  php:
    build: php
    container_name: php-aulasweb3
    restart: always
    depends_on:
      - mysql
      - node
    volumes:
      - ./php:/var/php
    ports:
      - 41070:80
  node:
    build: node
    container_name: node-aulasweb3
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./node/src:/usr/src/app
    ports:
      - 41071:3000
  mysql:
    image: mysql:5.7
    container_name: mysql-aulasweb3
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 41072:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
